In [1]:
import numpy as np

# 逻辑运算

In [2]:
score = np.random.randint(40, 100, (10, 5))

In [3]:
score

array([[83, 47, 50, 80, 91],
       [48, 70, 90, 49, 53],
       [58, 83, 65, 92, 42],
       [69, 49, 98, 83, 44],
       [50, 66, 73, 76, 68],
       [49, 64, 86, 41, 59],
       [52, 60, 46, 60, 50],
       [49, 63, 75, 85, 90],
       [98, 92, 53, 41, 51],
       [46, 55, 68, 65, 67]])

In [4]:
test_score = score[6:, 0:5]

In [5]:
test_score

array([[52, 60, 46, 60, 50],
       [49, 63, 75, 85, 90],
       [98, 92, 53, 41, 51],
       [46, 55, 68, 65, 67]])

In [6]:
test_score > 60

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False,  True,  True,  True]])

In [7]:
test_score[test_score > 60] = 1

In [8]:
test_score

array([[52, 60, 46, 60, 50],
       [49,  1,  1,  1,  1],
       [ 1,  1, 53, 41, 51],
       [46, 55,  1,  1,  1]])

# 通用判断函数

In [9]:
np.all(score[0:2, :] > 60) # 判断前两名同学的成绩[0:2, :]是否全及格

False

In [10]:
np.any(score[0:2, :] > 90)# 判断前两名同学的成绩[0:2, :]是否有大于90分的

True

In [11]:
score 

array([[83, 47, 50, 80, 91],
       [48, 70, 90, 49, 53],
       [58, 83, 65, 92, 42],
       [69, 49, 98, 83, 44],
       [50, 66, 73, 76, 68],
       [49, 64, 86, 41, 59],
       [52, 60, 46, 60, 50],
       [49,  1,  1,  1,  1],
       [ 1,  1, 53, 41, 51],
       [46, 55,  1,  1,  1]])

In [12]:
np.any(score[0:2, :] > 90)

True

# np.where（三元运算符）

In [13]:
temp = score[:4, :4]

In [14]:
temp

array([[83, 47, 50, 80],
       [48, 70, 90, 49],
       [58, 83, 65, 92],
       [69, 49, 98, 83]])

In [15]:
np.where(temp > 60, 1, 0)

array([[1, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 1]])

In [16]:
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[1, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1]])

In [17]:
np.where(np.logical_or(temp > 90, temp < 60), 1, 0)

array([[0, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0]])

# 统计运算

In [18]:
temp = score[:4, :]

In [19]:
temp

array([[83, 47, 50, 80, 91],
       [48, 70, 90, 49, 53],
       [58, 83, 65, 92, 42],
       [69, 49, 98, 83, 44]])

In [20]:
np.max(temp)

98

In [21]:
np.mean(temp)

67.2

In [22]:
np.max(temp, axis=0) #axis = 0为列，在这里代表各科成绩的最大分

array([83, 83, 98, 92, 91])

In [23]:
np.max(temp, axis=1) #axis = 1为行，在这里代表同学最高分的一门成绩

array([91, 90, 92, 98])

In [24]:
np.argmax(temp)

17

In [25]:
np.argmax(temp, axis=0)

array([0, 2, 3, 2, 0], dtype=int64)

In [26]:
np.argmin(temp, axis=0)

array([1, 0, 0, 1, 2], dtype=int64)

# 数组间的运算

In [27]:
a = np.array([[1,2,3],[3,4,5]])

In [28]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [29]:
a + 3

array([[4, 5, 6],
       [6, 7, 8]])

In [30]:
a / 2

array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5]])

In [31]:
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [32]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [33]:
# arr1 + arr2 # 不可以进行计算

In [34]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [35]:
arr1.shape

(2, 6)

In [36]:
arr2.shape #广播机制扩展数组

(2, 1)

In [37]:
arr2+arr

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

# 矩阵运算

In [38]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [39]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [40]:
b = np.array([[0.7], [0.3]])

In [41]:
b

array([[0.7],
       [0.3]])

In [42]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [43]:
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [44]:
c = 10

In [45]:
np.dot(c, a)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [46]:
# np.matmul(c, a)  # matmul不支持矩阵和标量的乘法